//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use crate::JobStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    Eq,
    DeriveEntityModel,
    Serialize,
    Deserialize,
    typed_builder :: TypedBuilder,
)]
#[sea_orm(table_name = "parse_jobs")]
/// Durable parse-job facts generated from the migration-owned PostgreSQL schema.
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub input_hash: String,
    /// Original display metadata is optional for jobs created before the workbench migration.
    #[builder(default)]
    pub filename: Option<String>,
    #[builder(default)]
    pub size_bytes: Option<i64>,
    /// Preserve this string-backed enum mapping when regenerating the entity; no database enum migration is needed.
    pub status: JobStatus,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    #[builder(default)]
    pub progress: Option<Json>,
    pub version: i64,
    pub attempts: i32,
    /// Monotonic elapsed milliseconds for the latest completed attempt; older or interrupted work has no measurement.
    #[builder(default)]
    pub duration_ms: Option<i64>,
    /// Hidden tombstones keep cursor anchors and prevent deleted idempotency keys from recreating work.
    #[builder(default)]
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[builder(default)]
    pub lease_token: Option<Uuid>,
    #[builder(default)]
    pub lease_until: Option<DateTimeWithTimeZone>,
    #[builder(default)]
    pub result_path: Option<String>,
    #[builder(default)]
    pub error: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
